#!/bin/bash
# Deploy blue and green versions
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
# Check logs for green deployment
kubectl get pods -l app=messaging-app-green -o name | xargs -I {} kubectl logs {}